### ISSUE TITLE
Have problem with install npm modules 

### ISSUE THREAD

**Issue by dev-frog** [SamsadSajid/kickstart#1]
![windows problem](https://user-images.githubusercontent.com/42280847/51021170-f88b1980-15aa-11e9-9631-c9b64aeecefc.PNG)

**Comment by SamsadSajid** [comment]
What is the version of your `node` and `npm`?

**Comment by dev-frog** [comment]
I fix the problem.. windows-build-tools have to install.
i fix with this command.
npm install --global windows-build-tools

@SamsadSajid

**Comment by SamsadSajid** [comment]
That's great! :smile:
